[tool]

[tool.poetry]
authors = ["Nateu"]
description = "BDD python"
name = "root"
version = "0.0.1"

[tool.poetry.dependencies]
python = "^3.8"
mamba = "^0.11.2"
expects = "^0.9.0"

[tool.poetry.dev-dependencies]
pytest = "==6.0.0"
